# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: trivy

on:
  pull_request:
  schedule:
    - cron: 0 2/4 * * 1-5 # '31 15 * * 6' - Run every hour to compare results
  workflow_dispatch:

jobs:
  trivy-image-scan:
    name: Trivy image scan
    runs-on: "ubuntu-20.04"
    permissions:
      contents: read  # for actions/checkout to fetch code
      security-events: write  # for github/codeql-action/upload-sarif to upload sarif results
      actions: read  # only required for a private repository by github/codeql-action/upload-sarif to get the action run status
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Build an image from Dockerfile
        run: |
          docker build -t tokle.dev/juice-shop:${{ github.sha }} .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@6e7b7d1fd3e4fef0c5fa8cce1229c54b2c9bd0d8
        with:
          image-ref: 'tokle.dev/juice-shop:${{ github.sha }}'
          scan-type: image
          format: 'sarif'
          output: 'trivy-image-results.sarif'
          severity: 'CRITICAL,HIGH'
          scanners: 'vuln,config,secret'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-image-results.sarif'

  trivy-repo-scan:
    name: Trivy repo scan (fs scan)
    runs-on: ubuntu-20.04
    permissions:
      contents: read  # for actions/checkout to fetch code
      security-events: write  # for github/codeql-action/upload-sarif to upload sarif results
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@6e7b7d1fd3e4fef0c5fa8cce1229c54b2c9bd0d8
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-fs-results.sarif'
          severity: 'CRITICAL'
          scanners: 'vuln,config,secret'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-fs-results.sarif'

  trivy-iac-scan:
    name: Trivy IaC scan
    runs-on: ubuntu-20.04
    permissions:
      contents: read  # for actions/checkout to fetch code
      security-events: write  # for github/codeql-action/upload-sarif to upload sarif results
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@6e7b7d1fd3e4fef0c5fa8cce1229c54b2c9bd0d8
        with:
          scan-type: 'config'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-iac-results.sarif'
          severity: 'CRITICAL'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-iac-results.sarif'

